version: '3.8'

services:
  llm-calculator:
    build: .
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
    volumes:
      # Mount database for persistence
      - ./llm_calculator.db:/app/llm_calculator.db
      - ./scripts/llm_calculator.db:/app/scripts/llm_calculator.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data: 